### ISSUE TITLE
How to reproduce the annotation-free result in Table 5 in the RegionPLC paper?

### ISSUE THREAD

**Issue by TianhangXiang** [CVMI-Lab/PLA#26]
Hi, I noticed that in the RegionPLC paper, there is a new annotation-free setting and result for PLA, which is 17.7 mIoU. How can I reproduce the result? Can it be reproduced by calculating the caption loss only?

**Comment by Dingry** [comment]
Yes. The simplest way is to set the segmentation loss to zero. Besides, we calculate iou on foreground classes only, ignoring wall and floor. You can set ignore_class_idx as [0,1,19] to implement it.

**Comment by TianhangXiang** [comment]
> Yes. The simplest way is to set the segmentation loss to zero. Besides, we calculate iou on foreground classes only, ignoring wall and floor. You can set ignore_class_idx as [0,1,19] to implement it.

Thank you for your response! I used the config spconv_clip_base15_caption_adamw.yaml and set the segmentation loss and binary loss to 0, and calculated the view-level caption and entity-level caption loss only, but I got the following results :(
![image](https://github.com/CVMI-Lab/PLA/assets/64124736/dfd9fdc6-8d65-482c-a13b-a05dbdcbadb6)
![image](https://github.com/CVMI-Lab/PLA/assets/64124736/b910ffcf-02c9-4003-9817-c0c9288cf6d0)
![image](https://github.com/CVMI-Lab/PLA/assets/64124736/2bee5f62-8aef-4015-8336-d4ba57cc9b4d)
I didn't set the ignore_class_idx to  [0,1,19],  which is [19] still. But I think that it is not the main cause. Are there any additional settings to reproduce the results: )?

**Comment by jihanyang** [comment]
I think there are a lot of details. For example, you need to remove binary head, since you do not need it, adjust the loss weight of caption head. I can provide our config for it, but there might include some unsupported features in PLA, and you need to modified them to support them. Some features are used on RegionPLC and not needed for reproducing PLA results in table 5.

```
_BASE_CONFIG_: cfgs/scannet_models/spconv_clip_adamw.yaml


DATA_CONFIG:
  # TODO: make base + novel = all.
  ignore_class_idx: [0,1, 19 ]

  CAPTION_INFO:

    KEY: [SCENE, VIEW, ENTITY]
  
    SCENE:
      ENABLED: False
      CAPTION_PATH: text_embed/caption.json

    VIEW:
      ENABLED: True
      CAPTION_PATH: text_embed/caption_2d.json
      IMAGE_CORR_PATH: scannetv2_matching_idx.pickle
      SELECT: hybrid
      NUM: 250
      RATIO: 0.5
      SAMPLE: 1
      GATHER_CAPTION: False

    ENTITY:
      ENABLED: True
      CAPTION_PATH: text_embed/caption_2d_intersect_v3.json
      IMAGE_CORR_PATH: scannetv2_matching_idx_intersect_v3.pickle
      SELECT: ratio
      NUM: 1
      RATIO: 1.0
    
    CAPTION_CORR_PATH_IN_ONE_FILE: True

MODEL:

  TASK_HEAD:
    NAME: TextSegHead
    EVAL_ONLY: True

  CAPTION_HEAD:
    NAME: CaptionHead
    POOLING_TYPE: avg
    FEAT_NORM: True
    LOGIT_SCALE:
      value: 100.0
      learnable: True
    CUDA_ENABLED: True
    POOL_OBJ: feat
    LOSS_FUNC: CrossEntropy
    LOSS_WEIGHT:
      SCENE: 0.1
      VIEW: 0.5
      ENTITY: 0.5
```
