### ISSUE TITLE
Missing caption_2d_intersect_v3.json

### ISSUE THREAD

**Issue by Outlying3720** [CVMI-Lab/PLA#45]
Hi, the caption file: `caption_2d_intersect_v3.json` and `scannetv2_matching_idx_intersect_v3.pickle` are missing. And I also want to know how to generate it?
Thanks!

**Comment by Outlying3720** [comment]
```
    ENTITY:
      ENABLED: False
      CAPTION_PATH: text_embed/caption_detic_crop_matching_idx.json
      IMAGE_CORR_PATH: scannetv2_detic_crop_matching_idx.pickle
```
is missing too
